global:
  scrape_interval: 10s # recolecta datos cada 10 segundos de spring boot actuators

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-service:8080', 'worker-service:8081', 'gateway:8080']